import json
import re
import sqlite3
from pathlib import Path
from datetime import datetime
from typing import Dict, List, Any
from ..core.models import UnifiedSession


class IndexBuilder:
    """Build search index for sessions."""

    def __init__(self, output_dir: Path):
        self.output_dir = output_dir
        self.index_path = output_dir / "index.json"
        self.sqlite_path = output_dir / "index.sqlite"

    def build_index(
        self, sessions: List[UnifiedSession], export_paths: Dict[str, Path]
    ) -> None:
        """Build and save the search index."""
        ignored_ids = self._load_ignored()
        if ignored_ids:
            sessions = [s for s in sessions if s.session_id not in ignored_ids]
        index = {
            "version": "1.0.0",
            "generated_at": datetime.now().isoformat(),
            "stats": self._compute_stats(sessions),
            "sessions": [],
            "search_index": {},
        }

        keyword_index: Dict[str, List[str]] = {}

        for session in sessions:
            export_path = export_paths.get(session.session_id, "")
            prompt_count = self._count_prompts(session)
            prompt_outline = self._extract_prompt_outline(session)
            inferred_title = self._infer_title(session, prompt_outline)

            # Extract keywords from content
            keywords = self._extract_keywords(session)

            session_entry = {
                "id": session.session_id,
                "tool": session.tool.value,
                "project": session.project_path,
                "thread_id": session.thread_id,
                "title": inferred_title,
                "created": session.created_at.isoformat(),
                "updated": session.last_updated.isoformat(),
                "messages": session.message_count,
                "prompts": prompt_count,
                "prompt_outline": prompt_outline,
                "export_path": str(export_path) if export_path else None,
                "keywords": keywords,
                "search_text": self._build_search_text(session),
            }
            index["sessions"].append(session_entry)

            # Build keyword index
            for kw in keywords:
                if kw not in keyword_index:
                    keyword_index[kw] = []
                keyword_index[kw].append(session.session_id)

        index["search_index"] = keyword_index

        # Save index
        self.output_dir.mkdir(parents=True, exist_ok=True)
        with open(self.index_path, "w", encoding="utf-8") as f:
            json.dump(index, f, indent=2)

        self._build_sqlite_index(sessions, export_paths)

    def _compute_stats(self, sessions: List[UnifiedSession]) -> Dict:
        """Compute statistics from sessions."""
        by_tool: Dict[str, int] = {}
        by_project: Dict[str, int] = {}

        for session in sessions:
            tool_name = session.tool.value
            by_tool[tool_name] = by_tool.get(tool_name, 0) + 1

            if session.project_path:
                by_project[session.project_path] = (
                    by_project.get(session.project_path, 0) + 1
                )

        return {
            "total_sessions": len(sessions),
            "total_messages": sum(s.message_count for s in sessions),
            "by_tool": by_tool,
            "by_project": by_project,
        }

    def _count_prompts(self, session: UnifiedSession) -> int:
        return session.user_prompt_count

    def _extract_prompt_outline(self, session: UnifiedSession) -> str:
        skip_markers = (
            "caveat: the messages below were generated by the user",
            "do not respond to these messages",
            "messages below were generated by the user while running local commands",
            "<command-name>",
            "<command-message>",
            "<command-args>",
            "# agents.md instructions",
            "agents.md instructions",
            "## instructions",
        )
        for msg in session.messages:
            role = getattr(msg, "role", None)
            if getattr(role, "value", role) != "user":
                continue
            text = (msg.content or "").strip()
            if not text:
                continue
            lowered = text.lower()
            if any(marker in lowered for marker in skip_markers):
                continue
            text = self._clean_title_text(text)
            if not text:
                continue
            if self._is_low_quality_title(text):
                continue
            return text[:140]
        return ""

    def _infer_title(self, session: UnifiedSession, prompt_outline: str) -> str:
        suffix = session.session_id[-8:] if session.session_id else "session"

        if session.title and session.title.strip():
            native = self._clean_title_text(session.title)
            if native and not self._is_low_quality_title(native):
                return native[:80]

        if prompt_outline:
            cleaned = self._clean_title_text(prompt_outline)
            if self._is_low_quality_title(cleaned):
                cleaned = ""
            if cleaned:
                base = cleaned[:64]
                if base.endswith(f"· {suffix}"):
                    return base
                return f"{base} · {suffix}"

        date_label = session.created_at.strftime("%Y-%m-%d")
        tool_label = session.tool.value.replace("-", " ").title()
        return f"{tool_label} {date_label} • {suffix}"

    def _clean_title_text(self, text: str) -> str:
        cleaned = re.sub(r"^\[Tool Result\]\s*", "", text or "").strip()
        cleaned = re.sub(r"```.*?```", " ", cleaned, flags=re.DOTALL)
        cleaned = re.sub(r"<[^>]+>", " ", cleaned)
        cleaned = cleaned.replace("`", " ")
        cleaned = re.sub(r"\s+", " ", cleaned).strip()
        return cleaned

    def _is_low_quality_title(self, text: str) -> bool:
        lowered = (text or "").lower().strip()
        if not lowered:
            return True

        normalized = re.sub(r"^[^a-z0-9]+", "", lowered)

        low_quality_prefixes = (
            "caveat: the messages below were generated",
            "user exited claude code session",
            "conversation started",
            "session ",
            "agents.md instructions",
            "instructions for /home",
            "command-name",
            "command-message",
            "command-args",
            "login successful",
            "invalid api key",
            "api error",
            "generate a file named agents.md",
        )
        if any(normalized.startswith(prefix) for prefix in low_quality_prefixes):
            return True

        low_quality_fragments = (
            "on-request workspace-write",
            "workspace-write restricted",
            "sandbox",
            "approval",
        )
        if any(fragment in normalized for fragment in low_quality_fragments):
            return True

        if len(lowered) < 8:
            return True

        alpha_chars = sum(1 for ch in lowered if ch.isalpha())
        if alpha_chars < max(3, len(lowered) // 6):
            return True

        return False

    def _extract_keywords(self, session: UnifiedSession) -> List[str]:
        """Extract searchable keywords from session."""
        keywords = set()

        # From title
        if session.title:
            words = re.findall(r"\b\w{3,}\b", session.title.lower())
            keywords.update(words)

        # From messages (limited to avoid huge indexes)
        for msg in session.messages[:20]:  # First 20 messages
            if not msg.content:
                continue
            words = re.findall(r"\b\w{4,}\b", msg.content.lower())
            keywords.update(words[:50])  # First 50 words per message

        # Filter out common words
        stopwords = {
            "this",
            "that",
            "with",
            "have",
            "will",
            "from",
            "they",
            "been",
            "were",
            "said",
            "each",
            "which",
            "their",
            "there",
            "would",
            "about",
        }
        keywords -= stopwords

        return list(keywords)[:100]  # Limit to 100 keywords

    def _build_search_text(self, session: UnifiedSession) -> str:
        parts: List[str] = []

        if session.title:
            parts.append(session.title)

        for msg in session.messages[:30]:
            if msg.content:
                parts.append(msg.content)

        text = " ".join(parts).lower()
        return text[:20000]

    def _build_sqlite_index(
        self, sessions: List[UnifiedSession], export_paths: Dict[str, Path]
    ) -> None:
        self.output_dir.mkdir(parents=True, exist_ok=True)

        conn = sqlite3.connect(self.sqlite_path)
        try:
            conn.execute("PRAGMA journal_mode=WAL;")
            conn.execute("PRAGMA synchronous=NORMAL;")
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS sessions (
                    id TEXT PRIMARY KEY,
                    tool TEXT,
                    project TEXT,
                    thread_id TEXT,
                    title TEXT,
                    created TEXT,
                    updated TEXT,
                    messages INTEGER,
                    prompts INTEGER,
                    prompt_outline TEXT,
                    export_path TEXT,
                    search_text TEXT
                )
            """
            )
            columns = {
                row[1] for row in conn.execute("PRAGMA table_info(sessions)").fetchall()
            }
            if "prompts" not in columns:
                conn.execute("ALTER TABLE sessions ADD COLUMN prompts INTEGER")
            if "prompt_outline" not in columns:
                conn.execute("ALTER TABLE sessions ADD COLUMN prompt_outline TEXT")
            conn.execute("DELETE FROM sessions")

            conn.execute(
                "CREATE INDEX IF NOT EXISTS idx_sessions_tool ON sessions(tool)"
            )
            conn.execute(
                "CREATE INDEX IF NOT EXISTS idx_sessions_project ON sessions(project)"
            )
            conn.execute(
                "CREATE INDEX IF NOT EXISTS idx_sessions_created ON sessions(created)"
            )
            conn.execute(
                "CREATE INDEX IF NOT EXISTS idx_sessions_thread_id ON sessions(thread_id)"
            )

            conn.execute(
                """
                CREATE VIRTUAL TABLE IF NOT EXISTS sessions_fts
                USING fts5(id, title, project, tool, search_text)
            """
            )
            conn.execute("DELETE FROM sessions_fts")

            rows = []
            fts_rows = []
            for session in sessions:
                export_path = export_paths.get(session.session_id, "")
                search_text = self._build_search_text(session)
                prompt_count = self._count_prompts(session)
                prompt_outline = self._extract_prompt_outline(session)
                inferred_title = self._infer_title(session, prompt_outline)
                rows.append(
                    (
                        session.session_id,
                        session.tool.value,
                        session.project_path,
                        session.thread_id,
                        inferred_title,
                        session.created_at.isoformat(),
                        session.last_updated.isoformat(),
                        session.message_count,
                        prompt_count,
                        prompt_outline,
                        str(export_path) if export_path else None,
                        search_text,
                    )
                )
                fts_rows.append(
                    (
                        session.session_id,
                        inferred_title or "",
                        session.project_path or "",
                        session.tool.value,
                        search_text,
                    )
                )

            conn.executemany(
                """
                INSERT OR REPLACE INTO sessions (
                    id, tool, project, thread_id, title, created, updated,
                    messages, prompts, prompt_outline, export_path, search_text
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
                rows,
            )
            conn.executemany(
                """
                INSERT INTO sessions_fts (id, title, project, tool, search_text)
                VALUES (?, ?, ?, ?, ?)
            """,
                fts_rows,
            )
            conn.commit()
        finally:
            conn.close()

    def _load_ignored(self) -> set:
        ignore_path = self.output_dir / "ignored.json"
        if not ignore_path.exists():
            return set()
        try:
            data = json.loads(ignore_path.read_text(encoding="utf-8"))
            if isinstance(data, dict):
                values = data.get("session_ids", [])
            else:
                values = data
            return set(values or [])
        except Exception:
            return set()
