from datetime import datetime

from lore.core.models import Role, Tool, UnifiedMessage, UnifiedSession
from lore.interfaces.web_services import (
    enrich_session_for_detail,
    normalize_session_messages_for_display,
)


def _msg(role: Role, content: str) -> UnifiedMessage:
    return UnifiedMessage(role=role, content=content, timestamp=datetime(2026, 3, 4, 12, 0, 0))


def _session(tool: Tool, messages):
    return UnifiedSession(
        tool=tool,
        session_id="ses-test",
        created_at=datetime(2026, 3, 4, 12, 0, 0),
        last_updated=datetime(2026, 3, 4, 12, 5, 0),
        messages=messages,
    )


def test_claude_display_formatter_strips_command_xml_tags():
    session = _session(
        Tool.CLAUDE_CODE,
        [_msg(Role.ASSISTANT, "<command-name>login</command-name> done")],
    )

    normalize_session_messages_for_display(session)

    assert "<command-name>" not in session.messages[0].content
    assert "done" in session.messages[0].content


def test_opencode_display_formatter_strips_caveat_prefix_for_user():
    session = _session(
        Tool.OPENCODE,
        [
            _msg(
                Role.USER,
                "Caveat: the messages below were generated by the user while running local commands\nPlease fix this pipeline",
            )
        ],
    )

    normalize_session_messages_for_display(session)

    assert "Caveat:" not in session.messages[0].content
    assert "Please fix this pipeline" in session.messages[0].content


def test_warp_display_formatter_drops_toolu_noise_messages():
    session = _session(Tool.WARP, [_msg(Role.ASSISTANT, "toolu_abc123")])

    normalize_session_messages_for_display(session)

    assert session.messages[0].content == ""


def test_opencode_assistant_file_update_noise_is_summarized():
    session = _session(
        Tool.OPENCODE,
        [
            _msg(
                Role.ASSISTANT,
                "\n".join(
                    [
                        "The file /tmp/a.py has been updated.",
                        "The file /tmp/b.py has been updated.",
                        "The file /tmp/c.py has been created.",
                    ]
                ),
            )
        ],
    )

    normalize_session_messages_for_display(session)

    assert "File operations summary" in session.messages[0].content
    assert "updated: `/tmp/a.py`" in session.messages[0].content


def test_opencode_unset_env_block_is_summarized():
    session = _session(
        Tool.OPENCODE,
        [
            _msg(
                Role.USER,
                "\n".join(
                    [
                        "AZURE_DEVOPS_PAT: not set",
                        "AZURE_DEVOPS_ORG_URL: not set",
                        "GITHUB_TOKEN: not set",
                        "SLACK_BOT_TOKEN: not set",
                    ]
                ),
            )
        ],
    )

    normalize_session_messages_for_display(session)

    assert "Unset environment variables" in session.messages[0].content
    assert "AZURE_DEVOPS_PAT" in session.messages[0].content


def test_strip_ansi_sequences_rule_applies():
    session = _session(
        Tool.OPENCODE,
        [_msg(Role.ASSISTANT, "\u001b[31mERROR\u001b[0m plain")],
    )

    normalize_session_messages_for_display(session)

    assert "\u001b" not in session.messages[0].content
    assert "ERROR" in session.messages[0].content


def test_claude_file_operation_summary_can_be_disabled():
    session = _session(
        Tool.CLAUDE_CODE,
        [
            _msg(
                Role.ASSISTANT,
                "\n".join(
                    [
                        "The file /tmp/one.py has been updated.",
                        "The file /tmp/two.py has been updated.",
                        "The file /tmp/three.py has been created.",
                    ]
                ),
            )
        ],
    )

    normalize_session_messages_for_display(
        session,
        noise_rules={
            "claude-code": {
                "claude_summarize_file_operations": False,
                "claude_strip_command_xml": True,
            },
            "default": {"strip_ansi_sequences": True},
        },
    )

    assert "File operations summary" not in session.messages[0].content
    assert "The file /tmp/one.py has been updated." in session.messages[0].content


def test_toc_labels_strip_leading_bracket_metadata():
    session = _session(
        Tool.OPENCODE,
        [
            _msg(Role.USER, "[search-model] [Image 1] Bitte mach das sauber"),
            _msg(Role.ASSISTANT, "Done"),
        ],
    )

    toc = enrich_session_for_detail(
        session,
        session_meta={},
        format_message_content_fn=lambda value: value,
        format_tool_calls_fn=lambda value: str(value),
        format_thinking_fn=lambda value: value,
    )

    assert toc
    assert toc[0]["text"] == "Bitte mach das sauber"


def test_claude_display_formatter_strips_caveat_prefix_for_user():
    """#68 — the Caveat boilerplate is stripped for Claude users too, not just opencode."""
    session = _session(
        Tool.CLAUDE_CODE,
        [
            _msg(
                Role.USER,
                "Caveat: The messages below were generated by the user while running "
                "local commands. DO NOT respond.\n\nActual question here?",
            )
        ],
    )

    normalize_session_messages_for_display(session)

    content = session.messages[0].content
    assert "Caveat: The messages below" not in content
    assert "Actual question here?" in content


def test_claude_command_only_message_is_folded_away():
    """#68 — a message that is only command bookkeeping renders empty, not a prompt card."""
    from lore.interfaces.web_services import _format_message_for_tool

    rendered = _format_message_for_tool(
        "claude-code",
        "user",
        "<command-name>/exit</command-name>\n<command-message>exit</command-message>\n"
        "<command-args></command-args>",
        {},
    )

    assert rendered == ""


def test_is_command_only_noise_detects_artifacts():
    from lore.interfaces.web_services import _is_command_only_noise

    assert _is_command_only_noise("[command: /exit]\n[exit]\n()")
    assert _is_command_only_noise("[command: /clear]")
    # Real content must NOT be folded.
    assert not _is_command_only_noise("[command: /exit]\nplease summarize the diff")
    assert not _is_command_only_noise("How do I fix the auth bug?")
    assert not _is_command_only_noise("")
